MyTest1/Controllers/客戶聯絡人Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using MyTest1.Models;

namespace MyTest1.Controllers
{
    public class 客戶聯絡人Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();
        // GET: 客戶聯絡人
        public ActionResult Index()
        {
            var all = db.客戶聯絡人.AsQueryable();
            var result = all.Where(c => c.是否已刪除 == false).OrderByDescending(c => c.Id).Take(10);
            return View(result);
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            string strKeyword = fc.Get("txtKeyword");
            var all = db.客戶聯絡人.AsQueryable();
            var result = all.Where(c => c.是否已刪除 == false
                & (
                    c.姓名.Contains(strKeyword)
                    | c.職稱.ToString().Contains(strKeyword)
                    | c.Email.ToString().Contains(strKeyword)
                    | c.手機.Contains(strKeyword)
                    | c.電話.Contains(strKeyword)
                    | c.客戶資料.客戶名稱.Contains(strKeyword)
                )
            )
                .OrderByDescending(c => c.Id);
            return View(result);
        }

        public ActionResult Create()
        {
            var all = db.客戶資料.AsQueryable();
            var client = all.Where(c => c.是否已刪除 == false).OrderByDescending(c => c.Id);
            SelectList sl = new SelectList(client, "ID", "客戶名稱");
            ViewBag.CategoryItems = sl;

            return View();
        }

        [HttpPost]
        public ActionResult Create(客戶聯絡人 contrct, FormCollection fc)
        {
            var all = db.客戶資料.AsQueryable();
            var client = all.Where(c => c.是否已刪除 == false).OrderByDescending(c => c.Id);
            SelectList sl = new SelectList(client, "ID", "客戶名稱");
            ViewBag.CategoryItems = sl;
            if (ModelState.IsValid)
            {
                contrct.客戶Id =Convert.ToInt32(fc.Get("ddlClient"));
                db.客戶聯絡人.Add(contrct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contrct);
        }

        public ActionResult Edit(int id)
        {
            var all = db.客戶資料.AsQueryable();
            var client = all.Where(c => c.是否已刪除 == false).OrderByDescending(c => c.Id);
            SelectList sl = new SelectList(client, "ID", "客戶名稱");
            ViewBag.CategoryItems = sl;
            var result = db.客戶聯絡人.Find(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(int id, 客戶聯絡人 contrct, FormCollection fc)
        {
            var all = db.客戶資料.AsQueryable();
            var client = all.Where(c => c.是否已刪除 == false).OrderByDescending(c => c.Id);
            SelectList sl = new SelectList(client, "ID", "客戶名稱");
            ViewBag.CategoryItems = sl;

            if (ModelState.IsValid)
            {
                var c = db.客戶聯絡人.Find(id);
                c.客戶Id = Convert.ToInt32(fc.Get("ddlClient"));
                c.職稱 = contrct.職稱;
                c.姓名 = contrct.姓名;
                c.Email = contrct.Email;
                c.手機 = contrct.手機;
                c.電話 = contrct.電話;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contrct);
        }

        public ActionResult Details(int id)
        {
            return View(db.客戶聯絡人.Find(id));
        }

        public ActionResult Delete(int id)
        {

            var client = db.客戶聯絡人.Find(id);
            client.是否已刪除 = true;
            try
            {
                db.SaveChanges();
            }
            catch (DbEntityValidationException ex)
            {
                throw ex;
            }
            return RedirectToAction("Index");
        }

    }
}

MyTest1/Controllers/客戶資料Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using MyTest1.Models;


namespace MyTest1.Controllers
{
    
    public class 客戶資料Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();
        // GET: 客戶資料
        public ActionResult Index()
        {
            var all = db.客戶資料.AsQueryable();
            var result = all.Where(c=>c.是否已刪除 == false).OrderByDescending(c => c.Id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            string strKeyword = fc.Get("txtKeyword");
            var all = db.客戶資料.AsQueryable();
            var result = all.Where(c => c.是否已刪除 == false 
                & (
                    c.客戶名稱.Contains(strKeyword) 
                    | c.統一編號.Contains(strKeyword)
                    | c.電話.Contains(strKeyword)
                    | c.傳真.Contains(strKeyword)
                    | c.地址.Contains(strKeyword)
                    | c.Email.Contains(strKeyword)
                )
            )
                .OrderByDescending(c => c.Id);
            return View(result);
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(客戶資料 client)
        {
            if (ModelState.IsValid)
            {
                db.客戶資料.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }


        public ActionResult Edit(int id)
        {
            return View(db.客戶資料.Find(id));
        }

        [HttpPost]
        public ActionResult Edit(int id, 客戶資料 client)
        {
            if (ModelState.IsValid)
            {
                var item = db.客戶資料.Find(id);
                item.客戶名稱 = client.客戶名稱;
                item.統一編號 = client.統一編號;
                item.電話 = client.電話;
                item.傳真 = client.傳真;
                item.地址 = client.地址;
                item.Email = client.Email;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        public ActionResult Details(int id)
        {
            return View(db.客戶資料.Find(id));
        }

        public ActionResult Delete(int id)
        {

            var client = db.客戶資料.Find(id);
            client.是否已刪除 = true;
            try
            {
                db.SaveChanges();
            }
            catch (DbEntityValidationException ex)
            {
                throw ex;
            }
            return RedirectToAction("Index");
        }


    }
}

MyTest1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 第一周作業</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("第一周作業", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("客戶資料管理", "Index", "客戶資料")</li>
                    <li>@Html.ActionLink("客戶聯絡人管理", "Index", "客戶聯絡人")</li>
                    <li>@Html.ActionLink("客戶銀行資訊管理", "Index", "客戶銀行資訊")</li>
                    <li>@Html.ActionLink("客戶摘要資訊", "Index", "客戶摘要資訊")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>